# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(919, 740)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(-5, -9, 971, 691))
        self.listWidget.setStyleSheet("background-color: rgb(57, 60, 68)")
        self.listWidget.setObjectName("listWidget")
        self.btnAddDialog = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAddDialog.setGeometry(QtCore.QRect(80, 20, 93, 28))
        self.btnAddDialog.setStyleSheet("border-radius:10px;background-color:rgb(31, 31, 31);COLOR:rgb(255, 255, 255)")
        self.btnAddDialog.setObjectName("btnAddDialog")
        self.btnXoaDialog = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnXoaDialog.setGeometry(QtCore.QRect(340, 20, 93, 28))
        self.btnXoaDialog.setStyleSheet("border-radius:10px;background-color:rgb(31, 31, 31);COLOR:rgb(255, 255, 255)")
        self.btnXoaDialog.setObjectName("btnXoaDialog")
        self.btnChinhSuaDialog = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnChinhSuaDialog.setGeometry(QtCore.QRect(630, 20, 93, 28))
        self.btnChinhSuaDialog.setStyleSheet("border-radius:10px;background-color:rgb(31, 31, 31);COLOR:rgb(255, 255, 255)")
        self.btnChinhSuaDialog.setObjectName("btnChinhSuaDialog")
        self.List_cook = QtWidgets.QListWidget(parent=self.centralwidget)
        self.List_cook.setGeometry(QtCore.QRect(75, 81, 781, 471))
        self.List_cook.setStyleSheet("border-radius:10px;background-color:rgb(31, 31, 31);color:rgb(255, 255, 255)")
        self.List_cook.setObjectName("List_cook")
        self.ValueSearch = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ValueSearch.setGeometry(QtCore.QRect(120, 570, 581, 41))
        self.ValueSearch.setStyleSheet("border-radius:10px;background-color:rgb(31, 31, 31);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.ValueSearch.setPlaceholderText("")
        self.ValueSearch.setObjectName("ValueSearch")
        self.btnsearch = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnsearch.setGeometry(QtCore.QRect(80, 560, 31, 61))
        self.btnsearch.setStyleSheet("border-radius:10px;background-color: rgb(57, 60, 68)")
        self.btnsearch.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/download/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnsearch.setIcon(icon)
        self.btnsearch.setObjectName("btnsearch")
        self.pushButton_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(810, 580, 111, 101))
        self.pushButton_back.setStyleSheet("background-color: rgb(57, 60, 68)")
        self.pushButton_back.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:/download/back-button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_back.setIcon(icon1)
        self.pushButton_back.setIconSize(QtCore.QSize(50, 100))
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_micro = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_micro.setGeometry(QtCore.QRect(710, 570, 51, 51))
        self.pushButton_micro.setStyleSheet("background-color: rgb(57, 60, 68)")
        self.pushButton_micro.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:/download/microphone.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_micro.setIcon(icon2)
        self.pushButton_micro.setIconSize(QtCore.QSize(40, 30))
        self.pushButton_micro.setObjectName("pushButton_micro")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 919, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnAddDialog.setText(_translate("MainWindow", "ADD"))
        self.btnXoaDialog.setText(_translate("MainWindow", "DELETE"))
        self.btnChinhSuaDialog.setText(_translate("MainWindow", "EDIT"))
