# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 604)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(-5, -9, 841, 571))
        self.listWidget.setStyleSheet("background-color: rgb(57, 60, 68)")
        self.listWidget.setObjectName("listWidget")
        self.btnAddDialog = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAddDialog.setGeometry(QtCore.QRect(80, 20, 93, 28))
        self.btnAddDialog.setStyleSheet("border-radius:10px;background-color:rgb(31, 31, 31);COLOR:rgb(255, 255, 255)")
        self.btnAddDialog.setObjectName("btnAddDialog")
        self.btnXoaDialog = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnXoaDialog.setGeometry(QtCore.QRect(340, 20, 93, 28))
        self.btnXoaDialog.setStyleSheet("border-radius:10px;background-color:rgb(31, 31, 31);COLOR:rgb(255, 255, 255)")
        self.btnXoaDialog.setObjectName("btnXoaDialog")
        self.btnChinhSuaDialog = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnChinhSuaDialog.setGeometry(QtCore.QRect(630, 20, 93, 28))
        self.btnChinhSuaDialog.setStyleSheet("border-radius:10px;background-color:rgb(31, 31, 31);COLOR:rgb(255, 255, 255)")
        self.btnChinhSuaDialog.setObjectName("btnChinhSuaDialog")
        self.List_cook = QtWidgets.QListWidget(parent=self.centralwidget)
        self.List_cook.setGeometry(QtCore.QRect(75, 81, 641, 441))
        self.List_cook.setStyleSheet("border-radius:10px;background-color:rgb(31, 31, 31);color:rgb(255, 255, 255)")
        self.List_cook.setObjectName("List_cook")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnAddDialog.setText(_translate("MainWindow", "ADD"))
        self.btnXoaDialog.setText(_translate("MainWindow", "DELETE"))
        self.btnChinhSuaDialog.setText(_translate("MainWindow", "EDIT"))
