# Form implementation generated from reading ui file 'ui/recipe_thit_kho.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_recipe(object):
    def setupUi(self, recipe):
        recipe.setObjectName("recipe")
        recipe.resize(1176, 828)
        self.centralwidget = QtWidgets.QWidget(parent=recipe)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(9, -1, 1171, 791))
        self.widget.setStyleSheet("border-radius:20px;background-color: rgb(57, 60, 68)")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setGeometry(QtCore.QRect(50, 50, 1101, 651))
        self.widget_2.setStyleSheet("background-color:rgb(31, 31, 31)\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(parent=self.widget_2)
        self.label.setGeometry(QtCore.QRect(430, 210, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(90, 250, 481, 361))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(550, 10, 541, 291))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("ui\\../../../Pictures/picture/sketchnote-cong-thuc-nau-an.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setObjectName("label_3")
        self.pushButton_back_2 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_back_2.setGeometry(QtCore.QRect(1050, 700, 101, 71))
        self.pushButton_back_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/download/back-button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_back_2.setIcon(icon)
        self.pushButton_back_2.setIconSize(QtCore.QSize(100, 50))
        self.pushButton_back_2.setObjectName("pushButton_back_2")
        recipe.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=recipe)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1176, 26))
        self.menubar.setObjectName("menubar")
        recipe.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=recipe)
        self.statusbar.setObjectName("statusbar")
        recipe.setStatusBar(self.statusbar)

        self.retranslateUi(recipe)
        QtCore.QMetaObject.connectSlotsByName(recipe)

    def retranslateUi(self, recipe):
        _translate = QtCore.QCoreApplication.translate
        recipe.setWindowTitle(_translate("recipe", "MainWindow"))
        self.label.setText(_translate("recipe", "Công Thức"))
        self.label_2.setText(_translate("recipe", "Cách làm:\n"
"\n"
"Sơ chế:\n"
"\n"
"Thịt ba chỉ rửa sạch, cắt miếng vuông vừa ăn.\n"
"Trứng vịt luộc chín, bóc vỏ.\n"
"Ướp thịt:\n"
"\n"
"Thịt ướp với 2 muỗng canh nước mắm, 1 muỗng canh đường, hành tím, tỏi, và ít tiêu. Ướp khoảng 30 phút cho thấm gia vị.\n"
"Kho thịt:\n"
"\n"
"Bắc nồi lên bếp, cho dầu ăn và nước màu vào, phi thơm hành tỏi.\n"
"Cho thịt đã ướp vào đảo cho săn lại.\n"
"Đổ nước dừa tươi vào, thêm ít nước lọc sao cho nước vừa ngập thịt.\n"
"Kho trứng:\n"
"\n"
"Khi nước sôi, hạ lửa nhỏ, kho liu riu khoảng 30 phút.\n"
"Cho trứng vịt vào kho chung, đậy nắp và tiếp tục kho đến khi thịt mềm và nước kho sánh lại."))
